In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('gas_prices.csv')
dataset

Year  Australia  Canada  France  Germany  Italy  Japan  Mexico  \
0   1990        NaN    1.87    3.63     2.65   4.59   3.16    1.00   
1   1991       1.96    1.92    3.45     2.90   4.50   3.46    1.30   
2   1992       1.89    1.73    3.56     3.27   4.53   3.58    1.50   
3   1993       1.73    1.57    3.41     3.07   3.68   4.16    1.56   
4   1994       1.84    1.45    3.59     3.52   3.70   4.36    1.48   
5   1995       1.95    1.53    4.26     3.96   4.00   4.43    1.11   
6   1996       2.12    1.61    4.41     3.94   4.39   3.64    1.25   
7   1997       2.05    1.62    4.00     3.53   4.07   3.26    1.47   
8   1998       1.63    1.38    3.87     3.34   3.84   2.82    1.49   
9   1999       1.72    1.52    3.85     3.42   3.87   3.27    1.79   
10  2000       1.94    1.86    3.80     3.45   3.77   3.65    2.01   
11  2001       1.71    1.72    3.51     3.40   3.57   3.27    2.20   
12  2002       1.76    1.69    3.62     3.67   3.74   3.15    2.24   
13  2003       2.19    1.99    4.35     4.59   4.53   3.47    2.04   
14  2004       2.72    2.37    4.99     5.24   5.29   3.93    2.03   
15  2005       3.23    2.89    5.46     5.66   5.74   4.28    2.22   
16  2006       3.54    3.26    5.88     6.03   6.10   4.47    2.31   
17  2007       3.85    3.59    6.60     6.88   6.73   4.49    2.40   
18  2008       4.45    4.08    7.51     7.75   7.63   5.74    2.45   

    South Korea    UK   USA  
0          2.05  2.82  1.16  
1          2.49  3.01  1.14  
2          2.65  3.06  1.13  
3          2.88  2.84  1.11  
4          2.87  2.99  1.11  
5          2.94  3.21  1.15  
6          3.18  3.34  1.23  
7          3.34  3.83  1.23  
8          3.04  4.06  1.06  
9          3.80  4.29  1.17  
10         4.18  4.58  1.51  
11         3.76  4.13  1.46  
12         3.84  4.16  1.36  
13         4.11  4.70  1.59  
14         4.51  5.56  1.88  
15         5.28  5.97  2.30  
16         5.92  6.36  2.59  
17         6.21  7.13  2.80  
18         5.83  7.42  3.27

In [4]:
df = dataset.drop(0)
df

Year  Australia  Canada  France  Germany  Italy  Japan  Mexico  \
1   1991       1.96    1.92    3.45     2.90   4.50   3.46    1.30   
2   1992       1.89    1.73    3.56     3.27   4.53   3.58    1.50   
3   1993       1.73    1.57    3.41     3.07   3.68   4.16    1.56   
4   1994       1.84    1.45    3.59     3.52   3.70   4.36    1.48   
5   1995       1.95    1.53    4.26     3.96   4.00   4.43    1.11   
6   1996       2.12    1.61    4.41     3.94   4.39   3.64    1.25   
7   1997       2.05    1.62    4.00     3.53   4.07   3.26    1.47   
8   1998       1.63    1.38    3.87     3.34   3.84   2.82    1.49   
9   1999       1.72    1.52    3.85     3.42   3.87   3.27    1.79   
10  2000       1.94    1.86    3.80     3.45   3.77   3.65    2.01   
11  2001       1.71    1.72    3.51     3.40   3.57   3.27    2.20   
12  2002       1.76    1.69    3.62     3.67   3.74   3.15    2.24   
13  2003       2.19    1.99    4.35     4.59   4.53   3.47    2.04   
14  2004       2.72    2.37    4.99     5.24   5.29   3.93    2.03   
15  2005       3.23    2.89    5.46     5.66   5.74   4.28    2.22   
16  2006       3.54    3.26    5.88     6.03   6.10   4.47    2.31   
17  2007       3.85    3.59    6.60     6.88   6.73   4.49    2.40   
18  2008       4.45    4.08    7.51     7.75   7.63   5.74    2.45   

    South Korea    UK   USA  
1          2.49  3.01  1.14  
2          2.65  3.06  1.13  
3          2.88  2.84  1.11  
4          2.87  2.99  1.11  
5          2.94  3.21  1.15  
6          3.18  3.34  1.23  
7          3.34  3.83  1.23  
8          3.04  4.06  1.06  
9          3.80  4.29  1.17  
10         4.18  4.58  1.51  
11         3.76  4.13  1.46  
12         3.84  4.16  1.36  
13         4.11  4.70  1.59  
14         4.51  5.56  1.88  
15         5.28  5.97  2.30  
16         5.92  6.36  2.59  
17         6.21  7.13  2.80  
18         5.83  7.42  3.27

In [17]:
X = df.iloc[:, 0].values
y = df.iloc[:, 1:].values
X

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008])

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1)

In [22]:
regressor = LinearRegression()
regressor.fit(X_train.reshape(-1,1), y_train)

LinearRegression()

In [15]:
y_pred = regressor.predict(X_test.reshape(-1, 1))
y_pred

array([[2.01228431, 1.80055881, 3.99574099, 3.70049651, 4.28958278,
        3.59384746, 1.62865396, 3.38591467, 3.85372097, 1.32845573],
       [1.62774967, 1.42974703, 3.44976591, 3.00362658, 3.83052671,
        3.36677176, 1.39473098, 2.73076836, 3.08919388, 0.98434774],
       [2.90953181, 2.66578629, 5.26968284, 5.32652634, 5.36071361,
        4.12369077, 2.17447423, 4.91458939, 5.63761752, 2.13137436],
       [1.49957146, 1.3061431 , 3.26777421, 2.77133661, 3.67750802,
        3.29107986, 1.31675665, 2.51238626, 2.83435152, 0.86964508]])

In [16]:
y_test

array([[2.05, 1.62, 4.  , 3.53, 4.07, 3.26, 1.47, 3.34, 3.83, 1.23],
       [1.84, 1.45, 3.59, 3.52, 3.7 , 4.36, 1.48, 2.87, 2.99, 1.11],
       [2.72, 2.37, 4.99, 5.24, 5.29, 3.93, 2.03, 4.51, 5.56, 1.88],
       [1.73, 1.57, 3.41, 3.07, 3.68, 4.16, 1.56, 2.88, 2.84, 1.11]])